export const metaElementsForHomePage: React.DetailedHTMLProps<
  React.MetaHTMLAttributes<HTMLMetaElement>,
  HTMLMetaElement
>[] = [
  {
    name: 'description',
    content: 'Generated by create next app',
  },
  {
    name: 'viewport',
    content: 'width=device-width, initial-scale=1',
  },
];
